name: Publish
on:
  workflow_run:
    workflows: ['Test']
    types: [completed]
    branches:
      - 'main'
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: Publish Logseq SPA
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: logseq/publish-spa@v0.3.1
        with:
          output-directory: dist
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/ --project-name=notes
  publish-data:
    runs-on: ubuntu-latest
    name: Publish Linked Data
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Export graph as RDF
        uses: logseq/rdf-export@main
        with:
          rdfFile: notes.ttl
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'notes.ttl'
          commit_message: "Update linked data"
