on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: Publish Logseq SPA
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: logseq/publish-spa@v0.3.1
        with:
          output-directory: dist
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/ --project-name=notes
