name: Test
on:
  push:
  pull_request:
    branches: [main]
jobs:
  spellcheck:
    name: Spellchecker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.32.0
  validate:
    name: Validate Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Graph Validation
        uses: logseq/graph-validator@main
